<?php declare(strict_types=1); ?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="csrf-token" content="<?= htmlspecialchars(csrf_token(), ENT_QUOTES, 'UTF-8') ?>">
<title>Fan Hub Plus — Member</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Barriecito&family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@600;700;800&display=swap">
<link rel="stylesheet" href="https://cdn-uicons.flaticon.com/uicons-regular-rounded/css/uicons-regular-rounded.css">
<link rel="stylesheet" href="https://unpkg.com/aos@2.3.4/dist/aos.css">
<link rel="stylesheet" href="/admin/assets/css/admin.css">
<link rel="stylesheet" href="/member/assets/css/member.css?v=member-rebuild20">
<link rel="stylesheet" href="/member/assets/css/member-fixes.css?v=member-rebuild20">
<link rel="stylesheet" href="/member/assets/css/member-avatar-fixes.css?v=member-rebuild20">
</head>
<body>
<div class="app-shell member-app">
  <header class="topbar"><a class="brand" href="/" aria-label="Fan Hub Plus home"><span>FanHubPlus</span></a><nav id="memberTopNav" class="top-shortcuts" aria-label="Member sections"></nav><div class="profile-wrap"><button id="memberProfileButton" class="profile-btn" type="button" aria-expanded="false"><span id="memberAvatar" class="avatar">M</span><span class="profile-copy"><strong id="memberName">Loading…</strong><small id="memberEmail">Loading profile…</small></span><i class="fi fi-rr-angle-small-down"></i></button><div id="memberProfileMenu" class="profile-menu"><a href="#profile"><i class="fi fi-rr-settings"></i>Profile settings</a><button id="darkModeTop" type="button"><i class="fi fi-rr-moon"></i>Dark mode</button><button id="logoutTop" type="button"><i class="fi fi-rr-sign-out-alt"></i>Log out</button></div></div></header>
  <aside id="memberRail" class="rail" aria-label="Member navigation"><button id="memberRailToggle" class="rail-toggle" type="button" aria-label="Expand navigation"><i class="fi fi-rr-menu-burger"></i><span class="nav-label">Menu</span></button><nav id="memberSideNav"></nav></aside>
  <main class="main">
    <section id="memberDashboardPage" class="page member-page" data-page="dashboard"><div class="page-head member-page-head"><div><p class="eyebrow">Member section</p><h1 id="memberGreeting">My Fandom Journey</h1><p id="memberFollowing">Your activity across Fan Hub Plus.</p></div><a class="primary" href="#explore"><i class="fi fi-rr-search"></i>Explore library</a></div><div class="dashboard-grid member-dashboard-grid"><div class="member-dashboard-main"><section class="pipeline-zone member-panel"><div class="section-title"><div><p class="eyebrow">Recent activity</p><h2>My Fandom Journey</h2></div><div class="view-toggle" role="group" aria-label="Activity layout"><button class="active" data-activity-view="grid" type="button" aria-label="Grid view"><i class="fi fi-rr-apps"></i></button><button data-activity-view="list" type="button" aria-label="List view"><i class="fi fi-rr-list"></i></button></div></div><div id="memberActivity" class="member-activity"></div></section><section class="member-panel member-bookmark-panel"><div class="section-title"><div><p class="eyebrow">Saved for later</p><h2>My Bookmarks</h2></div><a href="#bookmarks">View all <i class="fi fi-rr-arrow-up-right"></i></a></div><div id="memberBookmarkPreview" class="member-bookmark-preview"></div></section></div><aside class="member-dashboard-side"><section class="member-panel member-stats-panel"><div class="section-title"><div><p class="eyebrow">Your activity</p><h2>Stats</h2></div></div><div class="member-stats"><div class="stat stat-sky"><i class="fi fi-rr-bookmark"></i><strong data-stat="bookmarks">0</strong><span>Bookmarks</span></div><div class="stat stat-lav"><i class="fi fi-rr-star"></i><strong data-stat="ratings">0</strong><span>Ratings given</span></div><div class="stat stat-peach"><i class="fi fi-rr-edit"></i><strong data-stat="submissions">0</strong><span>Submissions</span></div><div class="stat stat-mint"><i class="fi fi-rr-time-forward"></i><strong data-stat="pending">0</strong><span>Pending review</span></div></div></section><section class="member-panel member-events-preview"><div class="section-title"><div><p class="eyebrow">Discover</p><h2>Upcoming events</h2></div><a href="#events" aria-label="View calendar"><i class="fi fi-rr-arrow-up-right"></i></a></div><div id="memberEventPreview" class="event-stack"></div></section></aside></div></section>
    <section id="memberContentPage" class="page member-page" data-page="content"><div class="page-head member-page-head"><div><p id="memberContentGroup" class="eyebrow">Discover</p><h1 id="memberContentTitle">Explore</h1><p id="memberContentDescription">Browse the complete library added by Fan Hub Plus admins.</p></div><div class="member-search"><i class="fi fi-rr-search"></i><input id="memberSearch" type="search" placeholder="Search anything…" autocomplete="off"></div></div><div id="memberContentTools" class="member-content-tools"></div><div id="memberContentList" class="member-content-list"></div></section>
  </main>
  <nav class="quickbar member-quickbar" aria-label="Quick add"><span class="quickbar-label">Quick add</span><button data-member-action="bookmark" data-tooltip="Add bookmark" aria-label="Add bookmark" type="button"><i class="fi fi-rr-bookmark"></i></button><button data-member-action="rating" data-tooltip="Rate media" aria-label="Rate media" type="button"><i class="fi fi-rr-star"></i></button><button data-member-action="submission" data-tooltip="Submit article" aria-label="Submit article" type="button"><i class="fi fi-rr-edit"></i></button><button data-member-action="feedback" data-tooltip="Send feedback" aria-label="Send feedback" type="button"><i class="fi fi-rr-comment-alt"></i></button><button id="darkModeQuick" data-tooltip="Dark mode" aria-label="Dark mode" type="button"><i class="fi fi-rr-moon"></i></button></nav>
  <div id="memberModal" class="modal-backdrop member-modal-backdrop" aria-hidden="true"><div class="modal member-modal" role="dialog" aria-modal="true" aria-labelledby="memberModalTitle"><div class="modal-head"><div><p class="eyebrow">Member action</p><h2 id="memberModalTitle">Action</h2></div><button id="memberModalClose" class="icon-btn" type="button" aria-label="Close"><i class="fi fi-rr-cross"></i></button></div><form id="memberModalForm"><div id="memberModalFields" class="form-grid"></div><div class="modal-actions"><button id="memberModalCancel" class="secondary" type="button">Cancel</button><button class="primary" type="submit"><i class="fi fi-rr-disk"></i>Save record</button></div></form></div></div>
  <div id="memberDetailModal" class="modal-backdrop member-modal-backdrop" aria-hidden="true"><div class="modal member-detail-modal" role="dialog" aria-modal="true" aria-labelledby="memberDetailTitle"><div class="modal-head"><div><p id="memberDetailBreadcrumbs" class="breadcrumb-line">Home &gt; Explore &gt; Content detail</p><p id="memberDetailType" class="eyebrow">Fan Hub Plus library</p><h2 id="memberDetailTitle">Content detail</h2></div><button id="memberDetailClose" class="icon-btn" type="button" aria-label="Close"><i class="fi fi-rr-cross"></i></button></div><div id="memberDetailBody" class="member-detail-body"></div></div></div>
</div>
<script src="https://unpkg.com/aos@2.3.4/dist/aos.js"></script><script src="/member/assets/js/member-avatar-fixes.js?v=member-rebuild20"></script><script src="/member/assets/js/member.js?v=member-rebuild20"></script>
</body>
</html>
